import pygame

BRUTEIMAGE = pygame.image.load("assets/brute.png")
CANNONIMAGE = pygame.image.load("assets/cannon.png")
ARCHERIMAGE = pygame.image.load("assets/archer.png")
BOXERIMAGE = pygame.image.load("assets/boxer.png")
SUPPORTIMAGE = pygame.image.load("assets/support.png")
DIAGONALIMAGE = pygame.image.load("assets/diagonal.png")
MIMICIMAGE = pygame.image.load("assets/mimic.png")
NINJAIMAGE = pygame.image.load("assets/ninja.png")
TRANSPORTERIMAGE = pygame.image.load("assets/transporter.png")
COMMONERIMAGE = pygame.image.load("assets/commoner.png")
CROWNIMAGE = pygame.image.load("assets/crown.png")
STOPIMAGE = pygame.image.load("assets/stop.png")

STARTIMAGE = pygame.image.load("assets/start.png")
CREATETEAMIMAGE = pygame.image.load("assets/teams.png")

IMAGELIST = [BRUTEIMAGE, CANNONIMAGE, ARCHERIMAGE, BOXERIMAGE, SUPPORTIMAGE, DIAGONALIMAGE, MIMICIMAGE, NINJAIMAGE, TRANSPORTERIMAGE, COMMONERIMAGE]

WIDTH, HEIGHT = 1920, 1080
SCREEN = pygame.display.set_mode((WIDTH, HEIGHT))
BOARDSTART = 600,180
BOARDEND = 1320,900
CHARACTERSTART = 360,930
POWERUPSTART = 100, 730
POWERUPBOARDSTART = 475, 600
ROWS = 6
COLS = 6
SQUARE_SIZE = 120
FPS = 60

# rgb
RED = (255, 0, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GREY = (128,128,128)

BUTTON = pygame.Surface((180, 120))

BRUTERECT = pygame.Rect(CHARACTERSTART[0], CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
CANNONRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 1), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
ARCHERRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 2), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
BOXERRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 3), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
SUPPORTRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 4), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
DIAGONALRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 5), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
MIMICRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 6), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
NINJARECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 7), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
TRANSPORTERRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 8), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)
COMMONERRECT = pygame.Rect(CHARACTERSTART[0] + (SQUARE_SIZE * 9), CHARACTERSTART[1], SQUARE_SIZE, SQUARE_SIZE)

CROWNRECT = pygame.Rect(480, 780, SQUARE_SIZE, SQUARE_SIZE)
CREATETEAMRECT = pygame.Rect(BOARDEND[0], BOARDEND[1] - SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE)
MOUSEPRESSED = pygame.mouse.get_pressed()[0]